# Generated by Django 5.0.14 on 2025-08-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('partner_organization', models.CharField(blank=True, max_length=150)),
                ('facility_type', models.CharField(choices=[('Lab', 'Lab'), ('Workshop', 'Workshop'), ('Testing Center', 'Testing Center'), ('Other', 'Other')], default='Lab', max_length=32)),
                ('capabilities', models.TextField(help_text='Comma-separated capabilities, e.g. CNC, PCB fabrication, materials testing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='facilities__name_412513_idx'), models.Index(fields=['facility_type'], name='facilities__facilit_dd5426_idx'), models.Index(fields=['partner_organization'], name='facilities__partner_583b5c_idx'), models.Index(fields=['location'], name='facilities__locatio_b28cee_idx')],
            },
        ),
    ]
